const e=s=>String(s??'—').replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]));
const fmt=x=>x==null?'—':Number(x).toLocaleString('ca',{maximumFractionDigits:2});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabpage').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')});
function line(points,lo,hi,w=620,h=180){if(!points?.length)return'';const span=hi-lo||1;return points.map((p,i)=>`${i*w/(points.length-1||1)},${h-(p.value-lo)*h/span}`).join(' ')}
function drawdowns(points){let peak=-Infinity;return points.map(x=>{peak=Math.max(peak,x.value);return{date:x.date,value:(x.value/peak-1)*100}})}
function chart(c){const vals=[...(c.asset||[]),...(c.strategy||[])].map(x=>x.value),lo=Math.min(...vals),hi=Math.max(...vals),dd=drawdowns(c.strategy),ddlo=Math.min(...dd.map(x=>x.value),-1);return `<div class="chart"><h4>Equity vs actiu</h4><svg viewBox="0 0 620 180" role="img" aria-label="Corba d'equity comparada amb comprar i mantenir"><polyline class="assetline" points="${line(c.asset,lo,hi)}"/><polyline class="strategyline" points="${line(c.strategy,lo,hi)}"/></svg><div class="legend"><span class="strategykey">Estratègia</span><span class="assetkey">Comprar i mantenir</span><span>Índex 100 · escala comuna ${fmt(lo)}–${fmt(hi)}</span></div><h4>Underwater / drawdown de l’estratègia</h4><svg class="underwater" viewBox="0 0 620 90" role="img" aria-label="Drawdown de l'estratègia"><line x1="0" y1="0" x2="620" y2="0"/><polyline class="ddline" points="${line(dd,ddlo,0,620,88)}"/></svg><div class="legend"><span class="ddkey">Caiguda des del màxim</span><span>Pitjor punt mensual ${fmt(ddlo)}%</span><span>2022 → 2024</span></div></div>`}
async function refresh(){try{const d=await(await fetch('/api/status',{cache:'no-store'})).json();
document.querySelector('#plain').textContent=d.plain_status;const ok=d.scheduler.status==='PASS';
document.querySelector('#health').textContent=ok?'TOT CORRECTE':'REVISAR';document.querySelector('#health').className=ok?'ok':'bad';
document.querySelector('#safety').textContent=`Ordres enviades: ${d.safety.orders_sent} · Broker connectat: NO · Paper/live: NO`;
document.querySelector('#strategies').innerHTML=d.strategies.map(s=>`<article class="card"><div class="top"><h3>${e(s.name)}</h3><span>${e(s.state)}</span></div><p>${e(s.explanation)}</p><dl><dt>Última acció</dt><dd>${e(s.last_action)}</dd><dt>Posició hipotètica</dt><dd>${s.position.quantity||0} unitats</dd><dt>Última sessió</dt><dd>${e(s.last_session)}</dd><dt>Següent</dt><dd>${e(typeof s.next_known_action==='object'?`${s.next_known_action.date} · ${s.next_known_action.action}`:s.next_known_action)}</dd></dl></article>`).join('');
const p=d.portfolio;document.querySelector('#portfolio').innerHTML=`<div><small>Període</small><b>${e(p.research_period)}</b></div><div><small>Retorn cartera</small><b>+${fmt(p.return_pct)}%</b></div><div><small>Profit factor</small><b>${fmt(p.profit_factor)}</b></div><div><small>Drawdown</small><b>${fmt(p.max_drawdown_pct_closed_equity)}%</b></div><div><small>Correlació</small><b>${fmt(p.correlation)}</b></div>`;
const c=d.scheduler;document.querySelector('#scheduler').innerHTML=`<dl><dt>Últim cicle</dt><dd>${e(c.ended_at)}</dd><dt>Pròxim cicle</dt><dd>${e(c.next_run_at)}</dd><dt>Freqüència</dt><dd>Cada hora</dd><dt>Estat</dt><dd>${e(c.status)}</dd></dl>`;
const a=d.asset_selection||{assets:[]};document.querySelector('#allocation').textContent=`Assignació de recerca: ${a.allocation}. Mateix període 2022–2024 per comparar sense barrejar finestres.`;
const sh=a.shared_account||{};document.querySelector('#shared').innerHTML=`<div><small>Retorn compte 40/40/20</small><b>${fmt(sh.return_pct)}%</b></div><div><small>Drawdown</small><b>${fmt(sh.max_drawdown_pct)}%</b></div><div><small>Capital mitjà ocupat</small><b>${fmt(sh.average_capital_deployed_pct)}%</b></div><div><small>Màxim ocupat</small><b>${fmt(sh.maximum_capital_deployed_pct)}%</b></div><div><small>Sessions coincidents</small><b>${fmt(sh.sessions_with_two_or_more_strategies)}</b></div>`;
document.querySelector('#assetcards').innerHTML=a.assets.map(x=>{const m=x.metrics,l=x.long_history,z=x.exposure||{};return `<article class="assetcard"><div class="assethead"><div><small>${e(x.kind)}</small><h3>${e(x.symbol)} <em>${e(x.allocation)}</em></h3></div><div class="assetmetrics"><b>${fmt(m.return_pct)}%</b><span>retorn net</span><b>${fmt(m.profit_factor)}</b><span>profit factor</span><b>${fmt(m.max_drawdown_pct_closed_equity)}%</b><span>drawdown</span><b>${m.events}</b><span>operacions</span><b>${fmt(z.time_in_market_pct)}%</b><span>temps exposat</span><b>${fmt(z.return_per_exposure_fraction_pct)}%</b><span>retorn / fracció exposada</span></div></div><p>${e(x.reason)}</p>${chart(x.chart)}<p class="note">${e(x.chart.note)}</p>${l?`<details><summary>MSFT: evidència històrica llarga</summary><p>${l.trades} operacions · ${(l.win_rate*100).toFixed(1)}% guanyadores · PF ${fmt(l.profit_factor)} · +${fmt(l.total_pct)}% · DD ${fmt(l.max_drawdown_pct)}%. Test aleatori p=${l.empirical_p.toFixed(4)}. Interval bootstrap EV: ${fmt(l.bootstrap_ev_95_bps[0])}–${fmt(l.bootstrap_ev_95_bps[1])} bps.</p></details>`:''}</article>`}).join('');
const corr=a.correlations||{};document.querySelector('#correlations').innerHTML='<h3>Diversificació</h3>'+Object.entries(corr).map(([k,v])=>`<p><span>${e(k.replaceAll('__',' ↔ '))}</span><b>${fmt(v.correlation_zero_when_inactive)}</b></p>`).join('');document.querySelector('#assetwarning').textContent=a.warning||'';
document.querySelector('#updated').textContent=`Panell actualitzat ${new Date(d.observed_at).toLocaleString('ca')}`;}catch(err){document.querySelector('#health').textContent='SENSE CONNEXIÓ';document.querySelector('#health').className='bad';}}
refresh();setInterval(refresh,5000);
